### ISSUE TITLE
Reviews for stage 3 sign off

### ISSUE THREAD

**Issue by leobalter** [sebmarkbage/ecmascript-string-left-right-trim#18]
I reviewed the spec text and this is good for Stage 3.

I believe @spectranaut can confirm the same.

**Comment by mathiasbynens** [comment]
I’d like to have clarification about the `name` of the aliased methods. [According to the proposal’s README](https://github.com/tc39/proposal-string-left-right-trim#naming--aliasing) the `String.prototype.trimLeft.name` should be `'trimStart'`, but the currently proposed spec text doesn’t make that happen.

+@sebmarkbage @evilpie @ljharb

**Comment by sebmarkbage** [comment]
The intention is that the spec ensures this by only defining trimStart/trimEnd. The aliases defined in annex B has the same object instance and therefore has to have the same name. Although I agree that it is not very clear.

**Comment by mathiasbynens** [comment]
I believe the current spec does not suffice normatively, because of <https://tc39.github.io/ecma262/#sec-ecmascript-standard-built-in-objects>:

> Every built-in function object, including constructors, that is not identified as an anonymous function has a name property whose value is a String. Unless otherwise specified, this value is the name that is given to the function in this specification. For functions that are specified as properties of objects, the name value is the property name string used to access the function.

**Comment by ljharb** [comment]
I think it does suffice; because the Start variants are defined first, with the Start names; and then later, in annex b, the Left variants are aliases to the pre-existing Start objects. This works for Array.prototype.values/Symbol.iterator, for example.

However, it might be a good idea to add explicit sentences in the Left variants indicating that their names are the Start variants.

**Comment by leobalter** [comment]
Can I suggest we reuse the language for [`Array#@@iterator`](https://tc39.github.io/ecma262/#sec-array.prototype-@@iterator)?

> The initial value of the @@iterator property is the same function object as the initial value of the Array.prototype.values property.

This would be an editorial change only in the proposal, so it shouldn't affect any in the stage process or merging it to the specs.

**Comment by ljharb** [comment]
That's exactly what it's saying already; I agree that making the wording match the existing cases of this pattern would be better.

**Comment by evilpie** [comment]
Okay, I guess I will prepare a PR for this wording change.

**Comment by evilpie** [comment]
See #25
