### ISSUE TITLE
Have we considered a paramater to the trimX() functions similar to C# usage.

### ISSUE THREAD

**Issue by JMcLauchlanSQ** [sebmarkbage/ecmascript-string-left-right-trim#22]
In C# you can very handily use .TrimStart("?"), this will remove specifically a "?" if it is at the beginning. This can be incredibly useful for very common cases where you want to remove starting string characters such as dealing with query urls on the web.
JS eg:
```
var query = ...;
if(query.indexOf("?") === -1)
    query = query.slice(1);
```
C# eg:
`var query = (...).TrimStart("?");`

Not sure if this has already been considered, just been using it a lot lately in C# and thought to check if it could be used in JS.

**Comment by ljharb** [comment]
This proposal is cementing something that's already shipped in all browsers for years. It'd need to be a separate proposal. (you can also do `.replace(/^?*/, '')`)

**Comment by JMcLauchlanSQ** [comment]
Ahhh, thanks for the quick response :)
